### ISSUE TITLE
Member.groups.fetch_all() fails with AttributeError: 'NoneType' object has no attribute 'update'

### ISSUE THREAD

**Issue by ptomblin** [myemma/EmmaPython#10]
I fetch a member using `pt = acct.members.find_one_by_email('pt...@gmail.com')` but when I attempt to find out what groups that person belongs to by using `pt.groups.fetch_all()` I get the above error, because `fetch_all -> paginated_get -> get_next -> get` and `get` is called with no params, and it's calling `params.update`.

Adding a `params = params or {}` line above the params.update line in emma/adaptor/request_adaptor.py line 105 fixed it for me.

**Comment by travishathaway** [comment]
Thanks for catching this bug and submitting a fix for it.  We will go ahead and merge your changes in to our repository.
