### ISSUE TITLE
Adding an existing member doesn't get the member_id populated

### ISSUE THREAD

**Issue by ptomblin** [myemma/EmmaPython#12]
If you create a `Member` with `factory()` with an existing email address, when you `save()` it, the `member_id` isn't populated because `outcome['added']` is `False`.

`
acct = Account(.....)
pt = acct.members.factory({'email': 'pt...@gmail.com'})
pt.save()
print(pt['member_id'])
`
Results in `KeyError: 'member_id'` if that email already exists in the Account. If the email doesn't exist, it prints the member id.

**Comment by travishathaway** [comment]
Thanks for the PR. This fix made sense to include in the master branch of the project.
